MaxSquadSize = 32
OrderRotationPeriod = 3 * 60 * 1000 -- 3 minutes in ms
FlagPriority = { Captured = 2, Enemy = 3, Neutral = 1 }
UnitClass = {
	Infantry      = "infantry",
	ATInfantry    = "at-infantry",
	Vehicle       = "vehicle",
	Tank          = "tank",
	AATank        = "aa-tank",
	ATTank        = "at-tank",
	HeavyTank     = "heavy-tank",
	ArtilleryTank = "artillery-tank",
	Sniper        = "sniper",
	Officer       = "officer",
	Airborne      = "airborne",
	Rare          = "rare",
	Howitzrer     = "howitzrer",
	MG            = "mg",
	Support       = "support",
	Mortar        = "mortar",
}

-- Wave phase config. `upto` is the exclusive upper time bound in seconds; the last
-- phase uses a huge bound. `targets` is the desired composition weight per tier;
-- only tiers listed participate. `waveMult` stretches the gap between waves as the match
-- matures (early 1.0, mid 1.5, late 2.25) so the bot banks MP for pricier units instead
-- of dribbling cheap ones to die. `squadCap` is the per-phase live-squad ceiling
-- (grows +2 per phase as the army gets pricier).
Phases = {
	{ name = "early", upto = 180,        targets = {                       light = 3, rifle = 3, smg = 1 }, budget = 14, waveMult = 1.0,  squadCap = 24, mainGroup = 4, subGroup = 3 },
	{ name = "mid",   upto = 480,        targets = {            medium = 2, light = 3, rifle = 1, smg = 1 }, budget = 22, waveMult = 1.5,  squadCap = 26, mainGroup = 5, subGroup = 4 },
	{ name = "late",  upto = 1000000000, targets = { heavy = 1, medium = 2, light = 3, rifle = 1, smg = 1 }, budget = 32, waveMult = 2.25, squadCap = 28, mainGroup = 6, subGroup = 4 },
}

-- Per-faction phase boundaries (seconds), anchored to real RobZ unlock times.
--   early -> mid = faction's first medium unlock.
--   mid   -> late = max(first HeavyTank-class unlock, first medium + 300s floor).
-- The 300s floor only binds eng (820 -> 1050) and rus (830 -> 1050), whose heavies
-- unlock right after their mediums. Japan has no HeavyTank unit, so its late anchors
-- to chi-to (1380) and its late composition drops the heavy tier (see lateTargets).
-- budget/waveMult/squadCap are NOT here; they stay shared on the global Phases template.
FactionPhases = {
	["eng"]       = { mid = 750, late = 1050 },
	["ger"]       = { mid = 630, late = 1500 },
	["ger_ss"]    = { mid = 630, late = 1500 },
	["usa"]       = { mid = 530, late = 1200 },
	["rus"]       = { mid = 750, late = 1050 },
	["jap"]       = { mid = 580, late = 1380,
	                  lateTargets = { medium = 2, light = 3, rifle = 1, smg = 1 } },
	["ger2"]      = { mid = 630, late = 1750 },
	["rus_guard"] = { mid = 750, late = 1240 },
}

Purchases = {

	{--single full roster, infinite (category-driven selection)
		Repeat = 0,
		Units = {
			["eng"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(eng)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(eng)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_at(eng)", line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_scot(eng)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="pioneers(eng)", inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(eng)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(eng)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(eng)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(eng)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(eng)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(eng)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="paratroopers(eng)", inf="rifle", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="mech_rifles(eng)", mech=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="stormtrooper5(eng)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(eng)",}, -- SAS Bren LMG team
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(eng)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(eng)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="paratroopers_drop(eng)",},
				{priority=1.5, class=UnitClass.Airborne,   unit="stormtroopers_drop(eng)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_eng_single", unlock=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="universal_carrier_seq", unlock=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="churchill_kangaroo", unlock=750,},
				{priority=1.5, class=UnitClass.Tank,       unit="mk7",                min_income=1.0, unlock=300,},
				{priority=1.5, class=UnitClass.Tank,       unit="m3stuart_eng",        min_income=1.0, unlock=460,},
				{priority=1.0, class=UnitClass.Tank,       unit="humber",              min_income=1.0, unlock=300,},
				{priority=1.0, class=UnitClass.Tank,       unit="staghound_seq",       min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.AATank,     unit="crusaderaa1",         min_income=1.5, unlock=520,},
				{priority=2.0, class=UnitClass.Tank,          unit="cromwell_mk_iv_seq",   min_income=1.5, unlock=750, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="mk3",                  min_income=1.5, unlock=480,},
				{priority=1.5, class=UnitClass.Tank,          unit="cromwell_mk_vi",        min_income=1.5, unlock=750, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a1_76w_eng",          min_income=1.5, unlock=1130, weight="medium",},
				{priority=1.0, class=UnitClass.Tank,          unit="cometa34",              min_income=2.0, unlock=1290, weight="medium",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="mk4",                  min_income=2.0, min_team=1, unlock=820,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="churchill_mk_vii",     min_income=2.0, min_team=1, unlock=1260,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="m4a4_firefly",         min_income=2.0, min_team=1, unlock=1780,},
				{priority=2.0, class=UnitClass.ATTank,        unit="m10wolverine_eng",     min_income=1.5, unlock=820,},
				{priority=1.5, class=UnitClass.ATTank,        unit="achilles",             min_income=1.5, unlock=1500,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="m7_eng", min_income=2.0, min_team=1, unlock=900, arty="field",},
			},
			["ger"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="volksgrens(ger)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="grenadiers_44(ger)", line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="volksgrens_sturm(ger)", line=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="fusiliers_44(ger)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="jagers_44(ger)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_44(ger)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers_44(ger)", smg=true, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="sturmgrens_44(ger)", phase="mid", inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmgrens_44_mech(ger)", mech=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="volksgrens_heavy(ger)", line=true, phase="early", inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="pzgren_pios(ger)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgsjager_44(ger)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="grenadiers_elite(ger)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgren_mech(ger)", mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper5(ger)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="fallschirm_mg(ger)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="gd_pzgren_mg(ger)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger)",},
				{priority=3.0, class=UnitClass.Mortar    ,   unit="light_mortar_ger", unlock=30,},
				{priority=1.0, class=UnitClass.MG      ,   unit="fallschirm_mg_39(ger)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(ger)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6_39(ger)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(ger)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_44_drop(ger)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_1", unlock=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz251_1_late_single", unlock=180,},
				-- support=true routes these three to the aux pool (bot.lua TierOf), where they
				-- compete purely by priority against ~7 duplicate MG entries + 3 AT entries above
				-- (each priority=1.0) plus sniper/flame, for only AuxPerCycle=2 picks per full
				-- ratio cycle. At the old priority=1.5 they were a small, easily-starved minority
				-- of that pool -- bumped to 2.5 (elite-infantry tier) so a support vehicle wins a
				-- meaningfully larger share of aux picks instead of reading as "never spawns".
				-- unlock times corrected to match the live mod's real .set data (were a flat
				-- 180s guess before; real unlock is per-unit and np_sdkfz234_3 in particular
				-- unlocks far later at 530s, not 180s).
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_10", unlock=240, support=true,},
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz251_9", unlock=370, support=true,},
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz234_3", unlock=530, support=true,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l",               min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz222",            min_income=1.0, unlock=380,},
				{priority=1.0, class=UnitClass.Tank,       unit="np_sdkfz234_1",       min_income=1.0, unlock=420,},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_m",               min_income=1.0, unlock=630, weight="medium",},
				{priority=1.5, class=UnitClass.AATank,     unit="welberwind",          min_income=1.5, unlock=420,},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4h_seq",             min_income=1.5, unlock=950, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="pz3n",                 min_income=1.5, unlock=630, weight="medium",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5g",                 min_income=2.0, min_team=1, unlock=1500,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6e",                 min_income=2.0, min_team=1, unlock=1750,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="sdkfz182b",            min_income=2.5, min_team=2, unlock=2160,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug3g_seq",           min_income=1.5, unlock=950,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer",               min_income=1.5, unlock=880,},
				{priority=1.5, class=UnitClass.ATTank,        unit="marder_3m",            min_income=1.5, unlock=750,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanzer_iv",        min_income=2.0, unlock=1500,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanther",          min_income=2.5, min_team=1, unlock=2000,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="wespe", min_income=2.0, min_team=1, unlock=900, arty="field",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="hummel", min_income=2.0, min_team=1, unlock=1200, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="sdkfz4", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				-- StuH42/Brummbär: close-support assault howitzers on a StuG/Panzer IV chassis.
				-- The mod's own .set groups these under a "medium" tank purchase button, but
				-- they are gun-howitzers, not line armor -- ArtilleryTank aux like the other
				-- self-propelled guns above, not a "medium" ratio-tier tank competing with
				-- pz3n/pz4h. assault=true: unlike wespe/hummel/sdkfz4 (indirect-fire, sit at a
				-- rear safe-band flag), these escort the main group and follow its target --
				-- direct-fire close support, not backline artillery. Excluded from GetArtyUnit
				-- (the backline trickle) and spawned instead via the assault-gun escort trickle.
				{priority=0.6, class=UnitClass.ArtilleryTank, unit="stuh42", min_income=1.5, min_team=1, unlock=880, arty="field", assault=true,},
				{priority=0.4, class=UnitClass.ArtilleryTank, unit="brummbar_early", min_income=2.0, min_team=1, unlock=1120, arty="heavy", assault=true,},
				{priority=1.0, class=UnitClass.AATank,        unit="ostwind",             min_income=1.5, unlock=520,},
			},
			["ger_ss"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="grenadiers_44(ger_ss)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="sturmgrens(ger_ss)", smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgrens_44(ger_ss)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgs_44(ger_ss)", inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="kosaken_44(ger_ss)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger_ss)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger_ss)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger_ss)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger_ss)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_44(ger_ss)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="lssah_pzgrens_44(ger_ss)", inf="rifle", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="tk_pzgrens_44(ger_ss)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmgrens_heavy(ger_ss)", inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgren_mech(ger_ss)", mech=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgs_cqc_44(ger_ss)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmpios(ger_ss)", inf="smg",},
				{priority=1.0, class=UnitClass.MG      ,   unit="tk_pzgren_mg(ger_ss)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="lssah_pzgren_mg(ger_ss)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger_ss)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger_ss)",},
				{priority=3.0, class=UnitClass.Mortar    ,   unit="5_cm_granatwerfer_36_ss", unlock=30,},
				{priority=1.0, class=UnitClass.MG      ,   unit="lssah_pzgren_mg_39(ger_ss)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="tk_pzgren_mg_39(ger_ss)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(ger_ss)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_44_drop(ger_ss)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_1", unlock=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="sdkfz251_1_late_ss", unlock=180,},
				-- SS gun-car equivalents of the ger support-vehicle trio (np_sdkfz250_10/251_9/
				-- 234_3): this roster never had any support=true entry at all, so the dedicated
				-- keep-alive trickle (bot.lua SupportVehicleIntervalSec) had nothing to spawn --
				-- read as "251/9 never spawns". np_sdkfz250_9 (2cm gun car) is ger_ss's real
				-- roster analog to ger's np_sdkfz250_10; np_sdkfz251_9/np_sdkfz234_3 share the
				-- same ids as ger. Unlock times per the live mod's real .set data.
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_9", unlock=320, support=true,},
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz251_9", unlock=370, support=true,},
				{priority=2.5, class=UnitClass.Vehicle,    unit="np_sdkfz234_3", unlock=530, support=true,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l",               min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz222",            min_income=1.0, unlock=380,},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_m_ss",            min_income=1.0, unlock=630, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="pz3n_ss",              min_income=1.5, unlock=630, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4g",                 min_income=1.5, unlock=830, weight="medium",},
				{priority=1.0, class=UnitClass.Tank,          unit="flammpz38",            min_income=1.5, unlock=900, weight="medium",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5a",                 min_income=2.0, min_team=1, unlock=1500,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6h",                 min_income=2.0, min_team=1, unlock=1750,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="pz6bh_ss",             min_income=2.5, min_team=2, unlock=2160,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer_ss",            min_income=1.5, unlock=880,},
				{priority=1.5, class=UnitClass.ATTank,        unit="marder_3m_ss",         min_income=1.5, unlock=750,},
				{priority=1.5, class=UnitClass.ATTank,        unit="stug3f",               min_income=1.0, unlock=830,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug4g",               min_income=1.5, unlock=950,},
				{priority=1.5, class=UnitClass.ATTank,        unit="jagdpanzer_iv_l48_ss",    min_income=1.5, unlock=950,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanzer_iv_ss",     min_income=2.0, unlock=1500,},
				{priority=1.0, class=UnitClass.ATTank,        unit="nashorn_ss",           min_income=2.0, min_team=1, unlock=1900,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanther_ss",       min_income=2.5, min_team=1, unlock=2000,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="wespe_ss", min_income=2.0, min_team=1, unlock=900, arty="field",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="hummel_ss", min_income=2.0, min_team=1, unlock=1200, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="sdkfz4_ss", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				-- StuH42/Brummbär (ss variants): same rationale as the ger entries above --
				-- ArtilleryTank aux, not "medium" armor, and assault=true so they escort the
				-- main group (close-support) instead of parking at a rear artillery flag.
				{priority=0.6, class=UnitClass.ArtilleryTank, unit="stuh42_ss", min_income=1.5, min_team=1, unlock=870, arty="field", assault=true,},
				{priority=0.4, class=UnitClass.ArtilleryTank, unit="brummbar_ss", min_income=2.0, min_team=1, unlock=1120, arty="heavy", assault=true,},
			},
			["usa"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(usa)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(usa)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_bar(usa)", line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_assault(usa)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="engineers(usa)", inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(usa)",},
				{priority=0.8, class=UnitClass.ATInfantry, unit="shotguns(usa)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(usa)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(usa)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(usa)", inf="smg", elite=true,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_101st(usa)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(usa)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="stormtroopers_heavy(usa)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="devils_brigade(usa)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="mech_armor_rifles(usa)", mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper5(usa)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper_at(usa)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(usa)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(usa)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="elite3b(usa)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(usa)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_drop(usa)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_101st_drop(usa)",},
				{priority=1.5, class=UnitClass.Airborne,   unit="paramarines_drop(usa)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_usa_seq", unlock=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m2halftrack", unlock=240,},
				{priority=1.5, class=UnitClass.Tank,       unit="m8grayhound",         min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="m5a1",                min_income=1.0, unlock=460,},
				{priority=1.0, class=UnitClass.Tank,       unit="m8",                  min_income=1.0, unlock=530, weight="medium",},
				{priority=1.0, class=UnitClass.Tank,       unit="m24",                 min_income=1.0, unlock=620,},
				{priority=1.5, class=UnitClass.AATank,     unit="m16",                 min_income=1.5, unlock=360,},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a3_75_seq",          min_income=1.5, unlock=750, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a3e8_seq",           min_income=1.5, unlock=1120, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a3_105",             min_income=1.5, unlock=950, weight="medium",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="m4a3e2_jumbo",        min_income=2.0, min_team=1, unlock=1200,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="m26_pershing",        min_income=2.5, min_team=1, unlock=1780,},
				{priority=2.0, class=UnitClass.ATTank,        unit="m18",                  min_income=1.5, unlock=820,},
				{priority=1.5, class=UnitClass.ATTank,        unit="m10wolverine",         min_income=1.5, unlock=820,},
				{priority=1.0, class=UnitClass.ATTank,        unit="m36",                  min_income=2.0, min_team=1, unlock=1500,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="m7", min_income=2.0, min_team=1, unlock=900, arty="field",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="m12gmc", min_income=2.5, min_team=1, unlock=1200, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="m4a3c", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="np_t19", min_income=2.0, min_team=1, unlock=900, arty="field",},
			},
			["rus"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(rus)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(rus)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgsv2(rus)", line=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="shock_assault(rus)", inf="smg", elite=true,},
				{priority=1.0, class=UnitClass.Infantry,   unit="sapper_squad(rus)", inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(rus)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(rus)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(rus)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(rus)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(rus)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="shock(rus)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="bsf_marines(rus)", inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgsv3(rus)", inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="shock_assault_mech(rus)", mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_riflesv2(rus)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(rus)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(rus)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="paras_drop(rus)",},
				{priority=1.5, class=UnitClass.Tank,       unit="t60",                 min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="t70",                 min_income=1.0, unlock=440,},
				{priority=1.0, class=UnitClass.Tank,       unit="bt5",                 min_income=1.0, unlock=440,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_seq",            min_income=1.5, unlock=750, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_3_seq",            min_income=1.5, unlock=1170, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="kv1",                  min_income=1.5, unlock=750, weight="heavy",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv2",                  min_income=1.5, min_team=1, unlock=830,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv85",                 min_income=2.0, min_team=1, unlock=1240,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="is1",                  min_income=2.0, min_team=1, unlock=1500,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is2",                  min_income=2.5, min_team=1, unlock=2160,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su85",                 min_income=1.5,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su76",                 min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="isu122",               min_income=2.5, min_team=1,},
				-- su122: closed-casemate 122mm howitzer on a T-34 hull, the direct Soviet
				-- counterpart to StuH42 -- direct-fire infantry support, escorts the main
				-- group rather than sitting backline (see the ger stuh42/brummbar comment).
				-- su152/isu152 are left as backline artillery: closer to a tank-hunting
				-- assault gun with longer engagement range than su122/StuH42.
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="su122", min_income=2.0, min_team=1, unlock=1120, arty="field", assault=true,},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="su152", min_income=2.0, min_team=1, unlock=1120, arty="heavy",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="isu152", min_income=2.0, min_team=1, unlock=1120, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm13", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm_8_24", min_income=2.0, min_team=1, unlock=900, arty="rocket",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm8-48", min_income=2.0, min_team=1, unlock=900, arty="rocket",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="np_bm31", min_income=2.5, min_team=1, unlock=1200, arty="rocket",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="280br5", min_income=2.5, min_team=1, unlock=1200, arty="heavy",},
			},
			["jap"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(jap)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans_t96(jap)", line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgs(jap)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards(jap)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(jap)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(jap)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(jap)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(jap)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(jap)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elites_takasago(jap)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(jap)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="elites_ig(jap)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="stormtrooper5(jap)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="teishin_at_rifles(jap)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(jap)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(jap)",},
				{priority=3.0, class=UnitClass.Mortar    ,   unit="type89mortarinf(jap)",},
				{priority=3.0, class=UnitClass.Mortar    ,   unit="type89mortarinfx2(jap)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg3(jap)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(jap)",},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_drop(jap)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="ho-ha3mgun_single", unlock=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="type97", unlock=30,},
				{priority=1.5, class=UnitClass.Tank,       unit="ss-d",                min_income=1.0, unlock=300, weight="light",},
				{priority=1.5, class=UnitClass.Tank,       unit="ha-go_seq",           min_income=1.0, unlock=300, weight="light",},
				{priority=1.5, class=UnitClass.Tank,       unit="chi-ha57",            min_income=1.0, unlock=480, weight="light",},
				{priority=1.0, class=UnitClass.Tank,       unit="chi-ha47",            min_income=1.0, unlock=530, weight="light",},
				{priority=1.0, class=UnitClass.Tank,       unit="ke-nu",               min_income=1.0, unlock=360, weight="light",},
				{priority=1.5, class=UnitClass.AATank,     unit="isuzutx40_aa",        min_income=1.5, unlock=280,},
				{priority=2.0, class=UnitClass.Tank,          unit="chi-he",               min_income=1.5, unlock=580, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="chi-nu",               min_income=1.5, unlock=750, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="chi-ha120",            min_income=1.5, unlock=750, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="chi-to",               min_income=2.0, min_team=1, unlock=1380, weight="medium",},
				{priority=1.0, class=UnitClass.Tank,          unit="chi-ri",               min_income=2.0, min_team=1, unlock=1500, weight="medium",},
				{priority=2.0, class=UnitClass.ATTank,        unit="ho-ni1",               min_income=1.5, unlock=750,},
				{priority=1.5, class=UnitClass.ATTank,        unit="ho-ni_3",              min_income=1.5, unlock=750,},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="ha-to", min_income=2.0, min_team=1, unlock=1200, arty="heavy",},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="ho-ni2", min_income=2.0, min_team=1, unlock=900, arty="field",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="ho-ro", min_income=2.0, min_team=1, unlock=1200, arty="heavy",},
			},
			["ger2"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(ger2)", line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(ger2)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards(ger2)", line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards2(ger2)", line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger2)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger2)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger2)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger2)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(ger2)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(ger2)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elites_para(ger2)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="bazooker3(ger2)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles2(ger2)",},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger2)", flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger2)",},
				{priority=3.0, class=UnitClass.Mortar    ,   unit="5_cm_granatwerfer_36_ger2", unlock=30,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtroopers3(ger2)",},
				{priority=1.5, class=UnitClass.Vehicle,    unit="sdkfz250_1_single", unlock=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="kfz15_gun", unlock=30,},
				-- Same gap as ger_ss: no support=true entry existed, so the keep-alive trickle
				-- had nothing to spawn. sdkfz234_3 is ger2's confirmed real roster gun car
				-- (unlock per the live mod's .set data).
				{priority=2.5, class=UnitClass.Vehicle,    unit="sdkfz234_3", unlock=530, support=true,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l_ger2",          min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz234_1",         min_income=1.0, unlock=420, weight="light",},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_ger2",           min_income=1.0, unlock=630, weight="medium",},
				{priority=1.5, class=UnitClass.AATank,     unit="ostwind_ger2",       min_income=1.5, unlock=560,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_ger",           min_income=1.5, unlock=750, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4j_ger2",           min_income=1.5, unlock=830, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="pzkpfw756",           min_income=1.5, unlock=1120, weight="heavy",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5g_ger2",           min_income=2.0, min_team=1, unlock=1750,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6e_ger2",           min_income=2.0, min_team=1, unlock=1750,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="sdkfz182b_ger2",      min_income=2.5, min_team=2, unlock=2120,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug3g_ger2",         min_income=1.5, unlock=950,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer_ger2",         min_income=1.5, unlock=870,},
				{priority=1.0, class=UnitClass.ATTank,        unit="nashorn_ger2",        min_income=2.0, min_team=1, unlock=1900,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="wespe_ger2", min_income=2.0, min_team=1, unlock=900, arty="field",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="sdkfz138_1", min_income=2.0, min_team=1, unlock=900, arty="heavy",},
			},
			["rus_guard"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="specialinf(rus_guard)", line=true, inf="smg",},
				{priority=2.0, class=UnitClass.Infantry,   unit="specialinf_smg(rus_guard)", line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="guards_shock(rus_guard)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="sapper_squad(rus_guard)", inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(rus_guard)",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(rus_guard)",},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(rus_guard)",},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(rus_guard)",},
				{priority=2.5, class=UnitClass.Infantry,   unit="elite_guards(rus_guard)", inf="smg", elite=true,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elite_guards_smg(rus_guard)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elite_guards_shock(rus_guard)", inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="guards_shock_assault(rus_guard)", inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="elite_guards_shock_assault(rus_guard)", inf="smg", elite=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers_piat(rus_guard)",},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(rus_guard)",},
				-- unlock corrected 180->240 to match the live mod's real .set data (both actually
				-- unlock at 240s, not the flat 180s guess used when these were first added).
				{priority=2.5, class=UnitClass.Vehicle,    unit="m3a1scout_guard", unlock=240, support=true,},
				{priority=2.5, class=UnitClass.Vehicle,    unit="m3_guard", unlock=240, support=true,},
				{priority=1.5, class=UnitClass.Tank,       unit="t60_guard",     min_income=1.0, unlock=420,},
				{priority=1.5, class=UnitClass.Tank,       unit="t70_guard",     min_income=1.0, unlock=440,},
				{priority=1.0, class=UnitClass.ATTank,     unit="su76_guard",    min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a2",           min_income=1.5, unlock=750, weight="medium",},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_guard",    min_income=1.5, unlock=750, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="t34_3_guard",    min_income=1.5, unlock=1170, weight="medium",},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a2_76w",       min_income=1.5, unlock=1120, weight="medium",},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv85_guard",    min_income=2.0, min_team=1, unlock=1240,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is1_guard",     min_income=2.0, min_team=1, unlock=1570,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is2_guard",     min_income=2.5, min_team=1, unlock=2160,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su85_guard",    min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="isu122_guard",  min_income=2.5, min_team=1,},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="203b4_guard", min_income=2.5, min_team=1, unlock=1200, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm13_guard", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm_8_24_guard", min_income=2.0, min_team=1, unlock=1200, arty="rocket",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="bm8-48_guard", min_income=2.0, min_team=1, unlock=900, arty="rocket",},
				{priority=0.5, class=UnitClass.ArtilleryTank, unit="isu152_guard", min_income=2.0, min_team=1, unlock=1120, arty="heavy",},
				{priority=0.3, class=UnitClass.ArtilleryTank, unit="np_bm31_guard", min_income=2.5, min_team=1, unlock=1200, arty="rocket",},
				-- su122_guard: same rationale as the rus entry above -- escorts the main group.
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="su122_guard", min_income=2.0, min_team=1, unlock=1120, arty="field", assault=true,},
			},
		},
	},

}
