MaxSquadSize = 32
OrderRotationPeriod = 3 * 60 * 1000 -- 3 minutes in ms
FlagPriority = { Captured = 2, Enemy = 3, Neutral = 1 }
UnitClass = {
	Infantry      = "infantry",
	ATInfantry    = "at-infantry",
	Vehicle       = "vehicle",
	Tank          = "tank",
	AATank        = "aa-tank",
	ATTank        = "at-tank",
	HeavyTank     = "heavy-tank",
	ArtilleryTank = "artillery-tank",
	Sniper        = "sniper",
	Officer       = "officer",
	Airborne      = "airborne",
	Rare          = "rare",
	Howitzrer     = "howitzrer",
	MG            = "mg",
	Support       = "support",
	Mortar        = "mortar",
}

-- Wave phase config. `upto` is the exclusive upper time bound in seconds; the last
-- phase uses a huge bound. `targets` is the desired composition weight per tier;
-- only tiers listed participate. `armorCap` is the heaviest tier allowed to spawn.
-- `waveMult` stretches the gap between waves as the match matures (early 1.0, mid 1.5,
-- late 2.25) so the bot banks MP for pricier units instead of dribbling cheap ones to die.
-- `squadCap` is the per-phase live-squad ceiling (grows +2 per phase as the army gets pricier).
Phases = {
	{ name = "early", upto = 180,        targets = {                       light = 1, rifle = 3, smg = 1 }, budget = 14, armorCap = "light",  waveMult = 1.0,  squadCap = 24 },
	{ name = "mid",   upto = 480,        targets = {            medium = 1, light = 2, rifle = 3, smg = 1 }, budget = 22, armorCap = "medium", waveMult = 1.5,  squadCap = 26 },
	{ name = "late",  upto = 1000000000, targets = { heavy = 1, medium = 1, light = 2, rifle = 3, smg = 1 }, budget = 32, armorCap = "heavy",  waveMult = 2.25, squadCap = 28 },
}

-- Tier rank for the armorCap gate (higher = heavier). Aux units are not gated here.
TierRank = { rifle = 0, smg = 0, light = 1, medium = 2, heavy = 3 }

-- Recharge seconds at/above which a class=Tank unit counts as medium (else light).
TierMediumRecharge = 550

Purchases = {

	{--single full roster, infinite (category-driven selection)
		Repeat = 0,
		Units = {
			["eng"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(eng)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(eng)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_at(eng)", recharge=0, line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_scot(eng)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="pioneers(eng)", recharge=0, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(eng)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(eng)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(eng)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(eng)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(eng)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(eng)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="paratroopers(eng)", recharge=0, inf="rifle", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="mech_rifles(eng)", recharge=0, mech=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="stormtrooper5(eng)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(eng)", recharge=0,}, -- SAS Bren LMG team
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(eng)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(eng)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="paratroopers_drop(eng)", recharge=0,},
				{priority=1.5, class=UnitClass.Airborne,   unit="stormtroopers_drop(eng)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_eng_single", recharge=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="universal_carrier_seq", recharge=180,},
				{priority=1.5, class=UnitClass.Tank,       unit="mk7", recharge=300,                min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="m3stuart_eng", recharge=460,        min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="humber", recharge=300,              min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="staghound_seq", recharge=420,       min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="crusaderaa1", recharge=520,         min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="cromwell_mk_iv_seq", recharge=750,   min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="mk3", recharge=480,                  min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="cromwell_mk_vi", recharge=750,        min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a1_76w_eng", recharge=1130,          min_income=1.5,},
				{priority=1.0, class=UnitClass.Tank,          unit="cometa34", recharge=1290,              min_income=2.0,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="mk4", recharge=820,                  min_income=2.0, min_team=1,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="churchill_mk_vii", recharge=1260,     min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="m4a4_firefly", recharge=1780,         min_income=2.0, min_team=1,},
				{priority=2.0, class=UnitClass.ATTank,        unit="m10wolverine_eng", recharge=820,     min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="achilles", recharge=1500,             min_income=1.5,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="m7_eng", recharge=900,              min_income=2.0, min_team=1,},
			},
			["ger"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="volksgrens(ger)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="grenadiers_44(ger)", recharge=0, line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="volksgrens_sturm(ger)", recharge=0, line=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="fusiliers_44(ger)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="jagers_44(ger)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_44(ger)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers_44(ger)", recharge=0, smg=true, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="sturmgrens_44(ger)", recharge=0, phase="mid", inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmgrens_44_mech(ger)", recharge=0, mech=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="volksgrens_heavy(ger)", recharge=0, line=true, phase="early", inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="pzgren_pios(ger)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgsjager_44(ger)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="grenadiers_elite(ger)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgren_mech(ger)", recharge=0, mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper5(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="fallschirm_mg(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="gd_pzgren_mg(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger)", recharge=0,},
				{priority=1.5, class=UnitClass.Mortar    ,   unit="light_mortar_ger", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="fallschirm_mg_39(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6_39(ger)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(ger)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_44_drop(ger)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_1", recharge=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz251_1_late_single", recharge=180,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l", recharge=420,               min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz222", recharge=380,            min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="np_sdkfz234_1", recharge=420,       min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_m", recharge=630,               min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="welberwind", recharge=420,          min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4h_seq", recharge=950,             min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="pz3n", recharge=630,                 min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5g", recharge=1500,                 min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6e", recharge=1750,                 min_income=2.0, min_team=1,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="sdkfz182b", recharge=2160,            min_income=2.5, min_team=2,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug3g_seq", recharge=950,           min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer", recharge=880,               min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="marder_3m", recharge=750,            min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanzer_iv", recharge=1500,        min_income=2.0,},
				{priority=1.0, class=UnitClass.ATTank,        unit="jagdpanther", recharge=2000,          min_income=2.5, min_team=1,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="wespe", recharge=900,               min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.AATank,        unit="ostwind", recharge=520,             min_income=1.5,},
			},
			["ger_ss"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="grenadiers_44(ger_ss)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="sturmgrens(ger_ss)", recharge=0, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgrens_44(ger_ss)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgs_44(ger_ss)", recharge=0, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="kosaken_44(ger_ss)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger_ss)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger_ss)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger_ss)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger_ss)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_44(ger_ss)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="lssah_pzgrens_44(ger_ss)", recharge=0, inf="rifle", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="tk_pzgrens_44(ger_ss)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmgrens_heavy(ger_ss)", recharge=0, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="pzgren_mech(ger_ss)", recharge=0, mech=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="gebirgs_cqc_44(ger_ss)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="sturmpios(ger_ss)", recharge=0, inf="smg",},
				{priority=1.0, class=UnitClass.MG      ,   unit="tk_pzgren_mg(ger_ss)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="lssah_pzgren_mg(ger_ss)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger_ss)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger_ss)", recharge=0,},
				{priority=1.5, class=UnitClass.Mortar    ,   unit="5_cm_granatwerfer_36_ss", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="lssah_pzgren_mg_39(ger_ss)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="tk_pzgren_mg_39(ger_ss)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(ger_ss)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_44_drop(ger_ss)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz250_1", recharge=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="np_sdkfz251_1_late_single", recharge=180,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l", recharge=420,               min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz222", recharge=380,            min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_m", recharge=630,               min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="welberwind", recharge=420,          min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4h_seq", recharge=950,             min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="pz3n", recharge=630,                 min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5g", recharge=1500,                 min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6e", recharge=1750,                 min_income=2.0, min_team=1,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="sdkfz182b", recharge=2160,            min_income=2.5, min_team=2,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug3g_seq", recharge=950,           min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer", recharge=880,               min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="jagdpanzer_iv_l48", recharge=950,    min_income=1.5,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="wespe", recharge=900,               min_income=2.0, min_team=1,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="stuh42", recharge=880,              min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.AATank,        unit="ostwind", recharge=520,             min_income=1.5,},
			},
			["usa"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(usa)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(usa)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_bar(usa)", recharge=0, line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="riflemans_assault(usa)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.Infantry,   unit="engineers(usa)", recharge=0, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(usa)", recharge=0,},
				{priority=0.8, class=UnitClass.ATInfantry, unit="shotguns(usa)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(usa)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(usa)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(usa)", recharge=0, inf="smg", elite=true,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites_101st(usa)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(usa)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="stormtroopers_heavy(usa)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="devils_brigade(usa)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="mech_armor_rifles(usa)", recharge=0, mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper5(usa)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="stormtrooper_at(usa)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(usa)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(usa)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="elite3b(usa)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg2(usa)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_drop(usa)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_101st_drop(usa)", recharge=0,},
				{priority=1.5, class=UnitClass.Airborne,   unit="paramarines_drop(usa)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_usa_seq", recharge=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m2halftrack", recharge=240,},
				{priority=1.5, class=UnitClass.Tank,       unit="m8grayhound", recharge=420,         min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="m5a1", recharge=460,                min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="m8", recharge=530,                  min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="m24", recharge=620,                 min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="m16", recharge=360,                 min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a3_75_seq", recharge=750,          min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a3e8_seq", recharge=1120,           min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a3_105", recharge=950,             min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="m4a3e2_jumbo", recharge=1200,        min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="m26_pershing", recharge=1780,        min_income=2.5, min_team=1,},
				{priority=2.0, class=UnitClass.ATTank,        unit="m18", recharge=820,                  min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="m10wolverine", recharge=820,         min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="m36", recharge=1500,                  min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="m7", recharge=900,                  min_income=2.0, min_team=1,},
			},
			["rus"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(rus)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(rus)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgsv2(rus)", recharge=0, line=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="shock_assault(rus)", recharge=0, inf="smg", elite=true,},
				{priority=1.0, class=UnitClass.Infantry,   unit="sapper_squad(rus)", recharge=0, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(rus)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(rus)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(rus)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(rus)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(rus)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="shock(rus)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="bsf_marines(rus)", recharge=0, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgsv3(rus)", recharge=0, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="shock_assault_mech(rus)", recharge=0, mech=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_riflesv2(rus)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(rus)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(rus)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="paras_drop(rus)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_rus_single", recharge=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3a1scout", recharge=240,},
				{priority=1.5, class=UnitClass.Tank,       unit="t60", recharge=420,                 min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="t70", recharge=440,                 min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="ba64", recharge=320,                min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="bt5", recharge=440,                 min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="dshk_stank", recharge=30,          min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_seq", recharge=750,            min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_3_seq", recharge=1170,            min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="kv1", recharge=750,                  min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv2", recharge=830,                  min_income=1.5, min_team=1,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv85", recharge=1240,                 min_income=2.0, min_team=1,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="is1", recharge=1500,                  min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is2", recharge=2160,                  min_income=2.5, min_team=1,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su85", recharge=0,                 min_income=1.5,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su76", recharge=0,                 min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="isu122", recharge=0,               min_income=2.5, min_team=1,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="su122", recharge=1120,               min_income=2.0, min_team=1,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="su152", recharge=1120,               min_income=2.5, min_team=1,},
			},
			["jap"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(jap)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans_t96(jap)", recharge=0, line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="smgs(jap)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards(jap)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(jap)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(jap)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(jap)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(jap)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(jap)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elites_takasago(jap)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(jap)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="elites_ig(jap)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="stormtrooper5(jap)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="teishin_at_rifles(jap)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(jap)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(jap)", recharge=0,},
				{priority=1.5, class=UnitClass.Mortar    ,   unit="type89mortarinf(jap)", recharge=0,},
				{priority=1.5, class=UnitClass.Mortar    ,   unit="type89mortarinfx2(jap)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mg3(jap)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtrooper6(jap)", recharge=0,},
				{priority=2.0, class=UnitClass.Airborne,   unit="elites_drop(jap)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="ho-ha3mgun_single", recharge=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="type97", recharge=30,},
				{priority=1.5, class=UnitClass.Tank,       unit="ha-go_seq", recharge=300,           min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="chi-ha57", recharge=480,            min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="chi-ha47", recharge=530,            min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="ke-nu", recharge=360,               min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="isuzutx40_aa", recharge=280,        min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="chi-he", recharge=580,               min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="chi-nu", recharge=750,               min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="chi-ha120", recharge=750,            min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="chi-to", recharge=1380,               min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.Tank,          unit="chi-ri", recharge=1500,               min_income=2.0, min_team=1,},
				{priority=2.0, class=UnitClass.ATTank,        unit="ho-ni1", recharge=750,               min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="ho-ni_3", recharge=750,              min_income=1.5,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="ho-ni2", recharge=900,              min_income=2.0, min_team=1,},
				{priority=0.8, class=UnitClass.ArtilleryTank, unit="ho-ro", recharge=1200,               min_income=2.0, min_team=1,},
			},
			["ger2"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="riflemans(ger2)", recharge=0, line=true, inf="rifle",},
				{priority=2.0, class=UnitClass.Infantry,   unit="smgs(ger2)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards(ger2)", recharge=0, line=true, inf="rifle",},
				{priority=1.5, class=UnitClass.Infantry,   unit="home_guards2(ger2)", recharge=0, line=true, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(ger2)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(ger2)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(ger2)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(ger2)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elites(ger2)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="stormtroopers(ger2)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elites_para(ger2)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.ATInfantry, unit="bazooker3(ger2)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles2(ger2)", recharge=0,},
				{priority=1.0, class=UnitClass.Infantry,   unit="flamers(ger2)", recharge=0, flame=true,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(ger2)", recharge=0,},
				{priority=1.5, class=UnitClass.Mortar    ,   unit="5_cm_granatwerfer_36_ger2", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="stormtroopers3(ger2)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="sdkfz250_1_single", recharge=180,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="kfz15_gun", recharge=30,},
				{priority=1.5, class=UnitClass.Tank,       unit="pz2l_ger2", recharge=420,          min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="sdkfz234_1", recharge=420,         min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="pz3_ger2", recharge=630,           min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="ostwind_ger2", recharge=560,       min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_ger", recharge=750,           min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="pz4j_ger2", recharge=830,           min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="pzkpfw756", recharge=1120,           min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="pz5g_ger2", recharge=1750,           min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="pz6e_ger2", recharge=1750,           min_income=2.0, min_team=1,},
				{priority=0.5, class=UnitClass.HeavyTank,     unit="sdkfz182b_ger2", recharge=2120,      min_income=2.5, min_team=2,},
				{priority=2.0, class=UnitClass.ATTank,        unit="stug3g_ger2", recharge=950,         min_income=1.5,},
				{priority=1.5, class=UnitClass.ATTank,        unit="hetzer_ger2", recharge=870,         min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="nashorn_ger2", recharge=1900,        min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="wespe_ger2", recharge=900,         min_income=2.0, min_team=1,},
			},
			["rus_guard"] = {
				{priority=2.0, class=UnitClass.Infantry,   unit="specialinf(rus_guard)", recharge=0, line=true, inf="smg",},
				{priority=2.0, class=UnitClass.Infantry,   unit="specialinf_smg(rus_guard)", recharge=0, line=true, smg=true, inf="smg",},
				{priority=1.5, class=UnitClass.Infantry,   unit="guards_shock(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="sapper_squad(rus_guard)", recharge=0, inf="rifle",},
				{priority=1.0, class=UnitClass.ATInfantry, unit="at_rifles(rus_guard)", recharge=0,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers(rus_guard)", recharge=0,},
				{priority=0.8, class=UnitClass.Sniper,     unit="snipers(rus_guard)", recharge=0,},
				{priority=0.3, class=UnitClass.Officer,    unit="officers(rus_guard)", recharge=0,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elite_guards(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=2.5, class=UnitClass.Infantry,   unit="elite_guards_smg(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="elite_guards_shock(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=2.0, class=UnitClass.Infantry,   unit="guards_shock_assault(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=1.5, class=UnitClass.Infantry,   unit="elite_guards_shock_assault(rus_guard)", recharge=0, inf="smg", elite=true,},
				{priority=1.0, class=UnitClass.ATInfantry, unit="bazookers_piat(rus_guard)", recharge=0,},
				{priority=1.0, class=UnitClass.MG      ,   unit="mgs2(rus_guard)", recharge=0,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3_guard", recharge=240,},
				{priority=1.5, class=UnitClass.Vehicle,    unit="m3a1scout_guard", recharge=240,},
				{priority=1.5, class=UnitClass.Tank,       unit="t60_guard", recharge=420,     min_income=1.0,},
				{priority=1.5, class=UnitClass.Tank,       unit="t70_guard", recharge=440,     min_income=1.0,},
				{priority=1.0, class=UnitClass.Tank,       unit="ba64_guard", recharge=320,    min_income=1.0,},
				{priority=1.5, class=UnitClass.AATank,     unit="dshk_stank_guard", recharge=30, min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,     unit="su76_guard", recharge=0,    min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="m4a2", recharge=750,           min_income=1.5,},
				{priority=2.0, class=UnitClass.Tank,          unit="t34_2_guard", recharge=750,    min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="t34_3_guard", recharge=1170,    min_income=1.5,},
				{priority=1.5, class=UnitClass.Tank,          unit="m4a2_76w", recharge=1120,       min_income=1.5,},
				{priority=1.5, class=UnitClass.HeavyTank,     unit="kv85_guard", recharge=1240,    min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is1_guard", recharge=1570,     min_income=2.0, min_team=1,},
				{priority=1.0, class=UnitClass.HeavyTank,     unit="is2_guard", recharge=2160,     min_income=2.5, min_team=1,},
				{priority=2.0, class=UnitClass.ATTank,        unit="su85_guard", recharge=0,    min_income=1.5,},
				{priority=1.0, class=UnitClass.ATTank,        unit="isu122_guard", recharge=0,  min_income=2.5, min_team=1,},
				{priority=1.0, class=UnitClass.ArtilleryTank, unit="su122_guard", recharge=1120,  min_income=2.0, min_team=1,},
			},
		},
	},

}
