-- GENERATED by tools/build_sectors.py. Do not edit by hand.
Sectors = {
  ["f1,f10,f2,f20,f3,f4,f5,f6,f7,f8,f9"] = {
    bases = {
      a1={x=-4300, y=-647},
      a2={x=-4300, y=746},
      b1={x=3931, y=-646},
      b2={x=3986, y=746},
    },
    flags = {
      f1={x=-212, y=-98, axis=0.50},
      f2={x=-618, y=-2952, axis=0.46},
      f3={x=-288, y=3674, axis=0.49},
      f4={x=573, y=-1945, axis=0.58},
      f5={x=-1738, y=1707, axis=0.32},
      f6={x=-1748, y=-1852, axis=0.33},
      f7={x=-357, y=-1284, axis=0.48},
      f8={x=-101, y=970, axis=0.51},
      f9={x=-66, y=2445, axis=0.51},
      f10={x=739, y=1705, axis=0.60},
      f20={x=-14, y=5042, axis=0.51},
    },
  },
}
