#!/usr/bin/env python3
"""Offline flag-sector extractor. Reads each map's battle_zones.mi from a RobZ map.pak,
computes per-flag axis (0 = A home, 1 = B home), and emits a flag_sectors.lua table.
Run by hand; the output is committed. This script never ships to the game."""
import re, math, zipfile, argparse

def parse_mi(text):
    """Return (bases, flags): name -> (x, y). Bases are a#/b#; flags are f#.
    Position may carry a third z value, which is ignored."""
    bases, flags = {}, {}
    for block in re.split(r"\{Entity ", text):
        nm = re.search(r"\{name\s+(\w+)\}", block)
        ps = re.search(r"\{Position\s+(-?[\d.]+)\s+(-?[\d.]+)", block)
        if not (nm and ps):
            continue
        name = nm.group(1)
        x, y = float(ps.group(1)), float(ps.group(2))
        if re.match(r"^[ab]\d+$", name):
            bases[name] = (x, y)
        elif re.match(r"^f\d+$", name):
            flags[name] = (x, y)
    return bases, flags

def _dist(p, q):
    return math.hypot(p[0] - q[0], p[1] - q[1])

def compute(bases, flags):
    """Return {name: (x, y, axis)}. Fails loudly if a side has no base."""
    A = [v for k, v in bases.items() if k[0] == "a"]
    B = [v for k, v in bases.items() if k[0] == "b"]
    if not A or not B:
        raise SystemExit("map missing a-base or b-base; refusing partial entry")
    out = {}
    for name, p in flags.items():
        dA = min(_dist(p, a) for a in A)
        dB = min(_dist(p, b) for b in B)
        out[name] = (p[0], p[1], dA / (dA + dB))
    return out

def fingerprint(flags):
    return ",".join(sorted(flags.keys()))

def emit_lua(entries):
    """entries: list of (fingerprint, bases, computed)."""
    out = ["-- GENERATED by tools/build_sectors.py. Do not edit by hand.", "Sectors = {"]
    for fp, bases, comp in entries:
        out.append('  ["%s"] = {' % fp)
        out.append("    bases = {")
        for k in sorted(bases):
            x, y = bases[k]
            out.append("      %s={x=%d, y=%d}," % (k, round(x), round(y)))
        out.append("    },")
        out.append("    flags = {")
        for k in sorted(comp, key=lambda s: int(s[1:])):
            x, y, axis = comp[k]
            out.append("      %s={x=%d, y=%d, axis=%.2f}," % (k, round(x), round(y), axis))
        out.append("    },")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("pak", help="path to RobZ map.pak")
    ap.add_argument("maps", nargs="+", help="map dir names under map/multi/")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()
    entries = []
    with zipfile.ZipFile(a.pak) as z:
        for m in a.maps:
            text = z.read("map/multi/%s/battle_zones.mi" % m).decode("latin-1")
            bases, flags = parse_mi(text)
            entries.append((fingerprint(flags), bases, compute(bases, flags)))
    with open(a.out, "w") as f:
        f.write(emit_lua(entries))
    print("wrote", a.out, "entries:", len(entries))

if __name__ == "__main__":
    main()
