#!/usr/bin/env python3
"""Offline flag-sector extractor. Reads each map's battle_zones.mi from a RobZ map.pak,
computes per-flag axis (0 = A home, 1 = B home), and emits a flag_sectors.lua table.
Run by hand; the output is committed. This script never ships to the game."""
import re, math, zipfile, argparse

def parse_mi(text):
    """Return (bases, flags): name -> (x, y). Bases are a#/b#; flags are f#.
    Position may carry a third z value, which is ignored."""
    bases, flags = {}, {}
    for block in re.split(r"\{Entity ", text):
        nm = re.search(r"\{name\s+(\w+)\}", block)
        ps = re.search(r"\{Position\s+(-?[\d.]+)\s+(-?[\d.]+)", block)
        if not (nm and ps):
            continue
        name = nm.group(1)
        x, y = float(ps.group(1)), float(ps.group(2))
        if re.match(r"^[ab]\d+$", name):
            bases[name] = (x, y)
        elif re.match(r"^f\d+$", name):
            flags[name] = (x, y)
    return bases, flags

def _dist(p, q):
    return math.hypot(p[0] - q[0], p[1] - q[1])

def compute(bases, flags):
    """Return {name: (x, y, axis)}. Fails loudly if a side has no base."""
    A = [v for k, v in bases.items() if k[0] == "a"]
    B = [v for k, v in bases.items() if k[0] == "b"]
    if not A or not B:
        raise SystemExit("map missing a-base or b-base; refusing partial entry")
    out = {}
    for name, p in flags.items():
        dA = min(_dist(p, a) for a in A)
        dB = min(_dist(p, b) for b in B)
        out[name] = (p[0], p[1], dA / (dA + dB))
    return out

def fingerprint(flags):
    return ",".join(sorted(flags.keys()))

THRESH = 2000.0
KFLOOR = 2

def _side_dist(flags, bases, name, side):
    ds = [_dist(flags[name], bp) for bn, bp in bases.items() if bn[0] == side]
    return min(ds) if ds else float("inf")

def adjacency(bases, flags):
    """Return {name: (nb_list, base_list)}. nb = flags within THRESH unioned with the
    KFLOOR nearest, made symmetric. base = sorted team letters whose base is within THRESH
    unioned with the KFLOOR nearest flags to each base (so every base labels at least its
    2 nearest flags)."""
    names = list(flags.keys())
    nb = {n: set() for n in names}
    for a in names:
        dists = sorted((_dist(flags[a], flags[b]), b) for b in names if b != a)
        for d, b in dists:
            if d < THRESH:
                nb[a].add(b)
        for d, b in dists[:KFLOOR]:
            nb[a].add(b)
    for a in names:                      # symmetrize
        for b in list(nb[a]):
            nb[b].add(a)
    base = {n: set() for n in names}
    for bname, bp in bases.items():
        dists_to_base = sorted((_dist(flags[n], bp), n) for n in names)
        close = {n for d, n in dists_to_base if d < THRESH}
        for _d, n in dists_to_base[:KFLOOR]:
            close.add(n)
        for n in close:
            base[n].add(bname[0])
    # dedupe: a flag tagged for both teams keeps only its nearer side (a wins exact ties)
    deduped = set()
    for n in names:
        if {"a", "b"} <= base[n]:
            deduped.add(n)
            da = _side_dist(flags, bases, n, "a")
            db = _side_dist(flags, bases, n, "b")
            base[n] = {"a"} if da <= db else {"b"}
    # trim: keep N = min(countA, countB) nearest flags per side, prioritizing deduped flags
    a_flags_deduped = sorted((n for n in names if base[n] == {"a"} and n in deduped),
                             key=lambda n: _side_dist(flags, bases, n, "a"))
    a_flags_regular = sorted((n for n in names if base[n] == {"a"} and n not in deduped),
                             key=lambda n: _side_dist(flags, bases, n, "a"))
    b_flags_deduped = sorted((n for n in names if base[n] == {"b"} and n in deduped),
                             key=lambda n: _side_dist(flags, bases, n, "b"))
    b_flags_regular = sorted((n for n in names if base[n] == {"b"} and n not in deduped),
                             key=lambda n: _side_dist(flags, bases, n, "b"))
    a_flags = a_flags_deduped + a_flags_regular
    b_flags = b_flags_deduped + b_flags_regular
    N = min(len(a_flags), len(b_flags))
    assert N >= 1, "a side or b side has no base flag"
    keep = set(a_flags[:N]) | set(b_flags[:N])
    for n in names:
        if base[n] and n not in keep:
            base[n] = set()
    key = lambda s: int(s[1:])
    return {n: (sorted(nb[n], key=key), sorted(base[n])) for n in names}

def emit_lua(entries):
    """entries: list of (key, bases, computed, adj)."""
    out = ["-- GENERATED by tools/build_sectors.py. Do not edit by hand.", "Sectors = {"]
    for mapkey, bases, comp, adj in entries:
        out.append('  ["%s"] = {' % mapkey)
        out.append("    bases = {")
        for k in sorted(bases):
            x, y = bases[k]
            out.append("      %s={x=%d, y=%d}," % (k, round(x), round(y)))
        out.append("    },")
        out.append("    flags = {")
        for k in sorted(comp, key=lambda s: int(s[1:])):
            x, y, axis = comp[k]
            nb, base = adj[k]
            nbstr = ",".join('"%s"' % n for n in nb)
            line = '      %s={x=%d, y=%d, axis=%.2f, nb={%s}' % (k, round(x), round(y), axis, nbstr)
            if base:
                line += ", base={%s}" % ",".join('"%s"' % t for t in base)
            line += "},"
            out.append(line)
        out.append("    },")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("pak", help="path to RobZ map.pak")
    ap.add_argument("maps", nargs="+", help="map dir names under map/multi/")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()
    entries = []
    with zipfile.ZipFile(a.pak) as z:
        for m in a.maps:
            text = z.read("map/multi/%s/battle_zones.mi" % m).decode("latin-1")
            bases, flags = parse_mi(text)
            entries.append((m, bases, compute(bases, flags), adjacency(bases, flags)))
    with open(a.out, "w") as f:
        f.write(emit_lua(entries))
    print("wrote", a.out, "entries:", len(entries))

if __name__ == "__main__":
    main()
